model_params:
  name: 'VanillaVAE'
  in_channels: 3
  latent_dim: 128
  img_size: 256

data_params:
  data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/cars_rendered_25k"
  train_batch_size: 256
  val_batch_size:  256
  patch_size: 256
  num_workers: 32


exp_params:
  LR: 0.0001
  weight_decay: 0.0
  # scheduler_gamma: 0.0
  # scheduler_gamma: 0.95
  kld_weight: 0.00025
  # kld_weight: 0.000
  manual_seed: 1265

trainer_params:
  gpus: [1]
  max_epochs: 1000

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  