model_params:
  name: 'VQVAE'
  in_channels: 3
  embedding_dim: 64
  # embedding_dim: 8
  # num_embeddings: 512
  num_embeddings: 256
  img_size: 256
  beta: 0.25

data_params:
  data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/cars_rendered_25k"
  # data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/real_cars_300"
  # data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/1k_sample_images_overall"
  # data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/plain_rotation_13_deg/Camera/80cae0cc66dcb8a88acb0ff76f4aec7d/"
  # data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/plain_rotation_13_deg/Camera/841d9f6bbe50ec6f122568beab222093/"
  # data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/plain_rotation_13_deg/Camera/6b7f573997bc6f8c953536e7c905b301/"
  # data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/plain_rotation_13_deg/Camera/7e63db420468e1b1bda733a39f84326d/"
  # data_path: "/data/rishubh/piyush/stylegan2-ada-pytorch/datasets/single_img/"
  train_batch_size: 80
  val_batch_size:  50
  # train_batch_size: 1
  # val_batch_size:  1
  patch_size: 256
  num_workers: 48


exp_params:
  LR: 0.0005
  # LR: 0.000
  weight_decay: 0.0
  # scheduler_gamma: 0.95
  scheduler_gamma: 0.0
  kld_weight: 0.00025
  manual_seed: 1265
  # resume: "/data/rishubh/piyush/PyTorch-VAE/logs/VQVAE/version_6/checkpoints/epoch=99-step=24499.ckpt"
  # resume: "/data/rishubh/piyush/PyTorch-VAE/logs/VQVAE/version_18_embedding_size_64/checkpoints/last.ckpt"

trainer_params:
  gpus: [0]
  max_epochs: 200
  # max_epochs: 1

logging_params:
  save_dir: "logs/"
  name: 'VQVAE'
